### ISSUE TITLE
Call fcm.registerForPushNotifications() AND Ti.Network.registerForPushNotifications() ?

### ISSUE THREAD

**Issue by garycrook** [hansemannn/titanium-firebase-cloud-messaging#10]
Hey @hansemannn I’m using this module on iOS. Do I need to call both fcm.registerForPushNotifications() *and* Ti.Network.registerForPushNotifications({success: function(e){}, error: function(e){}, callback: function(e){})?

**Comment by hansemannn** [comment]
Thats a very good question, and sorry for not answering on Slack so far. I would say, you should try to use both. The Ti.Network API also connects the Ti.Network events (like `remotenotification`), which is required to handle it via these. On the other hand, `registerForPushNotifications` will ensure that the internal Firebase API's are configured for push as well. Can you try it out?

**Comment by garycrook** [comment]
Thanks, yes I will be trying it on a real device shortly. When I call both `fcm.registerForPushNotifications()` and `Ti.Network.registerForPushNotifications()` on the simulator it fires the Ti.Network's error handler twice:
```
[INFO] :  push _onError: {"success":false,"code":3010,"source":{},"type":"remote","error":"remote notifications are not supported in the simulator"}
[INFO] :   push _onError: {"success":false,"code":3010,"source":{},"type":"remote","error":"remote notifications are not supported in the simulator"}
```
So I don't yet know whether it will fire the `remotenotification` push callback twice as well. Will let you know.

**Comment by Cratyz** [comment]
i also called them both, but then I removed one of them and it still works:

```
Ti.App.iOS.registerUserNotificationSettings({
            types: [
                Ti.App.iOS.USER_NOTIFICATION_TYPE_ALERT,
                Ti.App.iOS.USER_NOTIFICATION_TYPE_SOUND,
                Ti.App.iOS.USER_NOTIFICATION_TYPE_BADGE
            ]
        });
// fcm = firebase.cloudmessaging
        fcm.registerForPushNotifications();
```

AFTER this, i removed the `fcm.registerForPushNotifications()` as well and it STILL WORKS.
Simply doing:
```js
var core = require('firebase.core');
core.configure({
// your stuff here
});
var fcm = require('firebase.cloudmessaging');
fcm.addEventListener('didRefreshRegistrationToken', function (e) {
            Ti.API.info('!!!!!!!!!Token', e.fcmToken);
            console.log(e);
        });

        fcm.addEventListener('didReceiveMessage', function (e) {
            Ti.API.info('!!!!!!Message', e.message);
            console.log(e);
        });
```
is enough! I am really confused here. It seems that requiring the cloudmessaging module seems to be enough to trigger a `didRefreshRegistrationToken` event with an fcmToken. Something seems fundamentally faulty. Note that in the last codesample, there is no `registerUserNotificationSettings()` called, which means from a user perspective that you have registered with FCM although have not given permission to receive notifications. So I kinda wonder where the apnToken came from that is apparently used for registering with FCM.

I also got very confused by the readme, since there is a line saying "apnsToken (String, set) - iOS only", so I initally created a code snippet like:

```
Ti.Network.registerForPushNotifications({
  success: function(e) {
    // deviceToken here is an APN token.
    fcm.apnsToken = e.deviceToken; 
    fcm.registerForPushNotifications();
  }
});
```

This sample is very counterintuitive and calls registration twice (once for APN and once for FCM).

I'd like a neat code-example with no extraneous parts. Help is welcome

**Comment by Cratyz** [comment]
Follow up: none of the events give me any notification data. I am getting a notification when the ios app is in background (in foreground nothing happens), however none of the following events are called:

```js
// This one is called though, i am seeing an fcmToken.
//        fcm.addEventListener('didRefreshRegistrationToken', function (e) {
//            console.log('didRefreshRegistrationToken', e);
//        });

        fcm.addEventListener('didReceiveMessage', function (e) {
            console.log('didReceiveMessage', e);
        });

        Ti.App.iOS.addEventListener('notification', function (e) {
            console.log('notification', e);
        });

        Ti.App.iOS.addEventListener('remotenotificationaction', function (e) {
            console.log('remotenotificationaction', e);
        });

        Ti.App.iOS.addEventListener('localnotificationaction', function (e) {
            console.log('localnotificationaction', e);
        });
```

**Comment by Cratyz** [comment]
ok i got it to work on iOS, the only callback that catched the notification was:
```js
Ti.Network.registerForPushNotifications({
        success: ...,
        error: ...,
        callback: function(e) {
         // Notificationdata is received here.
        }
});
```

**Comment by hansemannn** [comment]
Folks, please make yourself familiar with remote push notifications in general before using this module. Obviously, `localnotificationaction` and `notification` do not fire in the background, since the first one is only triggered by local notification **actions** and the second one for notifications in the **foreground**. Also, as documented, `didReceiveMessage` is not called for push notifications but for direct messages via the `sendMessage` P2P API. Finally, `remotenotificationaction` is only fired when the user selects an **action** of a remote notification.

**Comment by Cratyz** [comment]
@hansemannn i have actually walked this path about 2 years ago, back then with `Ti.Goosh` module. It is not so much about being familiar with push notifications in general. The difficulty lies in the way we have to mix existing `Ti.Network` & `Ti.App.iOS` code with this module. Then we also have the android/ios discrepancy for which modules sometimes try to streamline it by using the same method names which actually work very different.

I would vouch for a code sample that actually works front-to-back. I currently have something working for iOS but it contains some parts where I cant tell what happens. I'll try out the swizzling parameter and see if that clears some of the code up.

**Comment by Cratyz** [comment]
https://gist.github.com/Cratyz/7198eed8f31a3cbd1cf6d9afbee65249

This is what I currently use. As you can see it follows the order: `Ti.App.iOS.registerUserNotificationSettings` -> `Ti.Network.registerForPushNotifications` -> `fcm.registerForPushNotifications`

**Comment by garycrook** [comment]
@hansemannn @Cratyz - it's all working for me now on iOS, I haven't tried on Android yet.

I created a CommonJS module: https://gist.github.com/garycrook/4b8c0f22b4f983c8fb2b5c643e6c30f5

Like @Cratyz I call things in the order 
`Ti.App.iOS.registerUserNotificationSettings -> Ti.Network.registerForPushNotifications -> fcm.registerForPushNotifications`

The `Ti.Network.registerForPushNotifications` callback is being fired for all scenarios: app in foreground, app backgrounded, app closed.

Hope you find it useful.

**Comment by hansemannn** [comment]
I have [updated the readme](https://github.com/hansemannn/titanium-firebase-cloud-messaging/commit/dc6ba28d16debf9c3aa03aee26d01480f647ee9c), thank you @garycrook !

**Comment by emmanuelfrancis** [comment]
I am integrating this module, I found that "didRefreshRegistrationToken" event does not get fired on iOS. It works fine on Android.
