### ISSUE TITLE
How to handle push messages

### ISSUE THREAD

**Issue by fahad86** [hansemannn/titanium-firebase-cloud-messaging#13]
Thanks a lot for this module.

The Documentation explicitly mentions that the **_didReceiveMessage_**  event is specifically for when direct messages arrive, and that they are different from push notifications.

The question that I have is how do we handle push notifications on **_Android_**?

Thanks and Regards

**Comment by Cratyz** [comment]
i am testing stuff out now with `Ti.App.iOS.addEventListener('remotenotificationaction')`. I am currently testing iOS since Android didnt quite build for me yet. It likely requires a different route.

https://docs.appcelerator.com/platform/latest/#!/api/Titanium.App.iOS-event-remotenotificationaction

(not sure if this works)

**Comment by fahad86** [comment]
@Cratyz why don't you download the latest stable build from here for android: https://github.com/hansemannn/titanium-firebase-cloud-messaging/releases ?

Do try to let me know how it goes.

**Comment by hansemannn** [comment]
@fahad86 Android uses services to receive the push notifications. @m1ga Implemented the android receivers and added may be able to assist here.

**Comment by m1ga** [comment]
```
fcm.addEventListener("didReceiveMessage", onMessage);
function onMessage(e) {
	alert("Got message: " + JSON.stringify(e.message));
}
```
will show the message as an alert when the app is in foreground. If the app is in background the phone will show the message the message for now (basic receive at the moment):
https://firebase.google.com/docs/cloud-messaging/android/receive#backgrounded

It should call the didReceiveMessage when you specify a data-field:
https://firebase.google.com/docs/cloud-messaging/android/receive#handling_messages
I didn't test (or implement) the `Messages with both notification and data payload, both background and foreground` part.

**Comment by m1ga** [comment]
BTW:
if you add this to your index:
```
var act = Titanium.Android.currentActivity;
var _intent = act.intent;
console.log(_intent.getStringExtra("test1"));
console.log(_intent.getStringExtra("test2"));
```

send a push with data -> test1 and test2 it will ouptput them when you click on the notification when your app is in backgorund.

**Comment by hansemannn** [comment]
Thanks for clarifying @m1ga !

**Comment by snehalhumne** [comment]
Hi @m1ga 

In cloud-push module, we have three events with which we can check if the app is started from a background or open from the killed state. and using these events we can manage the state of the app!

Is there a way we can add the same kind functionality to this module also?

Because whenever the app is in the background and we click on Firebase Push Notification it starts fro the index controller.
