### ISSUE TITLE
Resume backgrounded app from notifications click

### ISSUE THREAD

**Issue by tomjakobs1** [hansemannn/titanium-firebase-cloud-messaging#150]
Would it be possible to get instructions for how to get the app 
to resume when clicking on a notifcation on a backgrounded app ?

Thank you :)

Tom

**Comment by m1ga** [comment]
Hi @tomjakobs1 ,

please use Slack https://slack.tidev.io/ or the github discussions for such question as the `Issue` section is mainly for bugs/issues with the module.

As for the question:
It should do that automatically. If you have a notification and you click it it will start your app.  If it is still active it will bring it to the front otherwise it will restart it. If you send a normal notification on Android (in comparison to a data notification) it will restart your app all the time. We don't have control over that as the system handles those notifications.

**Comment by tomjakobs1** [comment]
Hello @m1ga. Sorry for that.
I will make sure to do that in the future.

**Comment by m1ga** [comment]
No problem! Hope it works already for you. Otherwise ask in the other channels and we'll search for a solution :)
